title:             Clean Blog
email:             vivien_tang@outlook.com
description:       Tang's Blog
author:            Vivien Tang
baseurl:           "/shuiyibuyi"
url:               "https://shuiyibuyi.github.io/"

# Social Profiles
Weibo_username: 镜面荆芥
github_username:   shuiyibuyi
WeChat_username: shuiyi1201


# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
